import { Metadata } from "next"
import Header from "./header"

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Next.js Tutorial - CodeVolution",
    template: "%s | Learning Next",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>

        <Header />

        {children}
        
        </body>
    </html>
  )
}
